//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    public partial class _Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblX;
        protected global::System.Web.UI.WebControls.TextBox txtX;
        protected global::System.Web.UI.WebControls.Label lblY;
        protected global::System.Web.UI.WebControls.TextBox txtY;
        protected global::System.Web.UI.WebControls.Button btnCalculate;
        protected global::System.Web.UI.WebControls.Label lblResult;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl q2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl q1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl q3;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl q4;
    }
}
